### ISSUE TITLE
shinydashboardPlus CRAN submission

### ISSUE THREAD

**Issue by DivadNojnarg** [cb4ds/periscope#41]
Hi,

I noticed that the package description mention shinydashboardPlus < 2.0.0, which is actually not a valid format. Only shinydashboardPlus >= or > is valid. 

I'll have to resubmit shinydashboardPlus on CRAN to fix a WARNING and NOTE issue due to a breaking change in a dependency. 

It will affect periscope. I started to work on a PR to ease the conversion and I'll submit as soon as possible.

Best

David

**Comment by cb4ds** [comment]
David,

It's my understanding that it is perfectly valid to have an upper bound on a package dependency [(see this link)](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies), and we are not limited to requiring only packages > or >=.  When we became aware that shinyDashboardPlus 2.x release will break our package we added the dependency version.  Can you point me to where you are getting information that our specification is invalid?  If it is I will be glad to update it.

Once shinydashboardPlus 2.x is out on CRAN we are planning to make a determination as to how to support it as a dependency going forward - we will likely need to support both the old and new versions for a period of time which is complicated and will require a significant package update on our end since this is a framework package.

**Comment by DivadNojnarg** [comment]
Hi Connie,
It was highlighted by the CRAN team upon shinydashboardPlus submission. The answer I got: "This is not possible, you can only have ">" or ">=" version dependencies.". 
I started to look at the repository, the "good" new it that you don't rely too deeply on shinydashboardPlus. Most of the breaking changes occur in the right sidebar, which was renamed to dashboardControlbar (like in bs4Dash), as well as the sidebar menu which now inherits from the classic shiny tabsetPanel. 
Feel free to contact me if you have any question. 
David 

    Le vendredi 5 mars 2021, 17:57:38 UTC+1, Dr. Connie Brett <notifications@github.com> a écrit :  
 
 


David,

It's my understanding that it is perfectly valid to have an upper bound on a package dependency (see this link), and we are not limited to requiring only packages > or >=. When we became aware that shinyDashboardPlus 2.x release will break our package we added the dependency version. Can you point me to where you are getting information that our specification is invalid? If it is I will be glad to update it.

Once shinydashboardPlus 2.x is out on CRAN we are planning to make a determination as to how to support it as a dependency going forward - we will likely need to support both the old and new versions for a period of time which is complicated and will require a significant package update on our end since this is a framework package.

**Comment by cb4ds** [comment]
Resolved in the latest release on CRAN (0.6.1)
